### ISSUE TITLE
Action fails with "Cannot send an empty message"

### ISSUE THREAD

**Issue by alexrp** [hugoalh/GitHubAction.SendToDiscord#19]
## Describe

Attempting to use this action results in:

```
Run hugoalh/GitHubAction.SendToDiscord@v1.1.6
  with:
    webhook_id: ***
    webhook_token: ***
    message_usetexttospeech: false
    message_embed_colour: INVISIBLE
    message_embed_field_0_isinline: false
    message_embed_field_1_isinline: false
    message_embed_field_2_isinline: false
    message_embed_field_3_isinline: false
    message_embed_field_4_isinline: false
    message_embed_field_5_isinline: false
    message_embed_field_6_isinline: false
    message_embed_field_7_isinline: false
    message_embed_field_8_isinline: false
    message_embed_field_9_isinline: false
    message_embed_field_10_isinline: false
    message_embed_field_11_isinline: false
    message_embed_field_12_isinline: false
    message_embed_field_13_isinline: false
    message_embed_field_14_isinline: false
    message_embed_field_15_isinline: false
    message_embed_field_16_isinline: false
    message_embed_field_17_isinline: false
    message_embed_field_18_isinline: false
    message_embed_field_19_isinline: false
    message_embed_field_20_isinline: false
    message_embed_field_21_isinline: false
    message_embed_field_22_isinline: false
    message_embed_field_23_isinline: false
    message_embed_field_24_isinline: false
    variable_prefix: %
    variable_suffix: %
    variable_join: _
Message embed field #0 is null, ignore remains.
Variable list #0 is null, ignore remains.
Status Code: 400
{"message": "Cannot send an empty message", "code": 50006}
```

## Version

v1.1.6

## To Reproduce

```yaml
name: News
on:
    issues:
        types:
            - opened
jobs:
    news:
        runs-on: windows-latest
        steps:
            - name: Notify Discord
              uses: hugoalh/GitHubAction.SendToDiscord@v1.1.6
              with:
                  webhook_id: ${{ secrets.DISCORD_NEWS_ID }}
                  webhook_token: ${{ secrets.DISCORD_NEWS_TOKEN }}
                  message_text: ${{ github.event.title }}
                  message_embed_authorname: ${{ github.event.user.login }}
                  message_embed_authorurl: ${{ github.event.user.html_url }}
                  message_embed_title: ${{ github.event.title }}
                  message_embed_titleurl: ${{ github.event.html_url }}
                  message_embed_description: ${{ github.event.body }}
```

Open an issue on the repo after adding this workflow.

## Expected Behavior

A message should be posted to Discord.

**Comment by hugoalh** [comment]
It seems you have some invalid codes... 🤔

From document "[Webhook events and payloads](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#issues)", `title`, `user.login`, `user.html_url`, `html_url`, and `body` should under `issue` object, that means should correct to this:

```yaml
name: News
on:
    issues:
        types:
            - opened
jobs:
    news:
        runs-on: windows-latest
        steps:
            - name: Notify Discord
              uses: hugoalh/GitHubAction.SendToDiscord@v1.1.6
              with:
                  webhook_id: ${{ secrets.DISCORD_NEWS_ID }}
                  webhook_token: ${{ secrets.DISCORD_NEWS_TOKEN }}
# Correction start here
                  message_text: ${{ github.event.issue.title }}
                  message_embed_authorname: ${{ github.event.issue.user.login }}
                  message_embed_authorurl: ${{ github.event.issue.user.html_url }}
                  message_embed_title: ${{ github.event.issue.title }}
                  message_embed_titleurl: ${{ github.event.issue.html_url }}
                  message_embed_description: ${{ github.event.issue.body }}
```
