### ISSUE TITLE
message_embed_colour seems to have become mandatory

### ISSUE THREAD

**Issue by alexrp** [hugoalh/GitHubAction.SendToDiscord#42]
After upgrading from `v1.1.6` to `v3.0.1`, I'm seeing:

```
SyntaxError: Configuration argument "embed#0.color"'s value is not an expected colour scheme! ([GitHub Action] Send To Discord)
```

Using:

```yaml
            - name: Notify Discord
              if: github.repository == 'flare-lang/flare-performance'
              uses: hugoalh/GitHubAction.SendToDiscord@v3.0.1
              with:
                  webhook_id: ${{ secrets.DISCORD_BENCHMARKS_ID }}
                  webhook_token: ${{ secrets.DISCORD_BENCHMARKS_TOKEN }}
                  message_embed_title: "Benchmarks: Reset"
                  message_embed_titleurl: https://performance.flare-lang.org
                  message_embed_description: Benchmark history has been reset.
```

(Only thing changed was the version number.)

Is this intended? I would have expected this to default to `"invisible"` as per [action.yml](https://github.com/hugoalh/GitHubAction.SendToDiscord/blob/master/action.yml#L56).

Side note: Should probably be consistent about `color` vs `colour` spelling.
